# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Devazul
email: jaimelopez.developer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Devazul is the personal blog, sort of portfolio, where I drop
  any kind of thought I can have about the tech world, software development,
  coding or any of my other interests.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.devazul.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DetectiveAzul
github_username:  DetectiveAzul
instagram_username: detective_azul
linkedin_username: jlopezrodriguez

google_analytics: UA-125274136-1
disqus_shortname: Devazul

# Build settings
markdown: kramdown
color_scheme: github

# theme: jekyll-theme-kagami
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
